# Native\u7F16\u8BD1\u4F18\u5316\u914D\u7F6E
quarkus.native.resources.includes=templates/**,META-INF/resources/**,*.html,*.css,*.js
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQLDialect
quarkus.log.file.enable=false
quarkus.log.level=INFO
quarkus.log.category."com.fun90.airopscat".level=INFO
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=4