payload:
  - 2caipiao.com
  - +.2caipiao.com
  - +.alsahm.com
  - +.alsahm.com.sa
  - +.aul711.com
  - +.hstong.com
  - +.hszq.com.cn
  - +.hszq6.com
  - +.hszq8.com
  - +.inzwc.com
  - +.mbkr.com.my
  - +.mgbl.com.my
  - +.mplusglobal.com.my
  - +.mplusonline.com.my
  - +.plusonline.com.my
  - +.tickrs.com.sg
  - +.vbkr.com
  - +.vbkrhk.com
  - +.vbkrsa.com
  - +.vbkrsg.com
  - +.vtradesa.com
  - +.vtradesg.com
  - +.vil-vbkr.com