payload:
  # private
  - clash.razord.top
  - yacd.haishan.me
  - download-cf.jetbrains.com
  - download.jetbrains.com
  - +.fun90.com
  - +.jetbrains-ls.org
  - +.duoyu.app
  - PROCESS-NAME,CorelDRW,DIRECT
  - +.zozo.jp
  - +.hsbc.com
  - +.hsbc.com.cn
  - +.hsbc.com.hk
  - lcs-cops.adobe.io
  - +.bvty.vip
  - +.bvty842.com
  - +.qyg.vip